[build]
  publish = "dist"
  command = "npm install --production=false && npm run build"
  # Alternative: command = "bash build.sh"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
